import "Navigation.JS";
// import "./Sidemenu.JS";
// import "./Scripts/Time.JS";
// import "./Header.JS";
// import "/Project/Scripts/Slideshow.JS";
// import "../Project/Scripts/Cards.JS";
// import "./Scripts/Main.JS";
// import "./Scripts/Footer.JS";
// import "./Scripts/Aboutme.JS";
// import "./Scripts/Form.JS";
// import "./Scripts/Socialmedia.JS";
// import "./Scripts/Disclaimer.JS";
// import "../Scripts/Copyright.JS"